#server portu ve hata mesajlarinin gosterilmesi icin ayarlar
server:
  port: 8080
  error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never

#spring boot uygulamasi icin ayarlar
spring:
  application:
    name: LibraryManagementSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/library_db
    username: techpro
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true

#loglama ayarlari slf4j
logging: #logging.file.name:log/studentapp.log
  file:
    name: log/libraryapp.log
  pattern:
    file: "%d %-5level [%thread] %logger:%msg%n"
  level:
    '[org.springframework.web]': WARN
    '[org.hibernate]': INFO
    #'[com.tpe]': INFO
    com:
      tpe: INFO

info:
  application:
    name: 'LibraryManagementSystem'
    version: '@project.version@'
    description: 'Library Management System'